services:
  api:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: syncly_sql
    environment:
      ACCEPT_EULA: "1"
      MSSQL_SA_PASSWORD: Leszczu2039#
    ports:
      - "1433:1433"
